package com.privacyshield.proxy

import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Intent
import android.net.VpnService
import android.os.Build
import android.os.ParcelFileDescriptor
import androidx.core.app.NotificationCompat
import com.privacyshield.proxy.core.MihomoCore
import com.privacyshield.proxy.core.RoutingConfig
import java.io.File

/**
 * Captures device traffic into a TUN and hands it to the Mihomo (Clash.Meta)
 * engine, which applies the rule map (per-app -> node, domain/ip/geo rules)
 * generated by RoutingConfig. Whole-device capture is used so Mihomo's rules
 * fully control routing; unmatched traffic hits the final MATCH,<finalTarget>.
 */
class ShieldVpnService : VpnService() {

    private var tun: ParcelFileDescriptor? = null
    private val watchdog = android.os.Handler(android.os.Looper.getMainLooper())

    companion object {
        const val ACTION_START = "com.privacyshield.proxy.START"
        const val ACTION_STOP = "com.privacyshield.proxy.STOP"
        private const val CHANNEL_ID = "shieldproxy_vpn"
        private const val NOTIF_ID = 1
        private const val WATCHDOG_MS = 20_000L

        @Volatile
        var running: Boolean = false
            private set

        /** True between an explicit Start and an explicit Stop. Used to auto-revive
         *  the engine if Android/Samsung kills it without the user asking. */
        @Volatile
        var wantRunning: Boolean = false
            private set

        /**
         * Cross-process "is the engine running?" — the service now lives in a separate ":vpn"
         * process (so a native engine crash can't kill the UI), which means the `running` static
         * above is NOT visible from the UI process. Ask ActivityManager instead (it reports our
         * own app's services across all processes).
         */
        fun isRunning(ctx: android.content.Context): Boolean {
            return try {
                val am = ctx.getSystemService(android.content.Context.ACTIVITY_SERVICE) as android.app.ActivityManager
                @Suppress("DEPRECATION")
                am.getRunningServices(Int.MAX_VALUE).any {
                    it.service.className == ShieldVpnService::class.java.name
                }
            } catch (_: Exception) {
                false
            }
        }
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        if (intent?.action == ACTION_STOP) {
            wantRunning = false
            stopTunnel()
            return START_NOT_STICKY
        }
        // ACTION_START, or a START_STICKY restart after the process was killed
        // (intent == null) — in that case revive from the persisted active profile.
        wantRunning = true
        startTunnel()
        scheduleWatchdog()
        return START_STICKY
    }

    /** Periodically ensure the engine is actually alive; revive it if it died
     *  while the user still wants it running. */
    private fun scheduleWatchdog() {
        watchdog.removeCallbacksAndMessages(null)
        watchdog.postDelayed(object : Runnable {
            override fun run() {
                if (!wantRunning) return
                if (!MihomoCore.running) {
                    // engine died on its own — rebuild the tunnel + restart Mihomo
                    stopEngineOnly()
                    startTunnel()
                }
                watchdog.postDelayed(this, WATCHDOG_MS)
            }
        }, WATCHDOG_MS)
    }

    private fun startTunnel() {
        // Switching lists: if already running, tear the engine down first and
        // re-establish with the newly-activated profile's config.
        if (running) stopEngineOnly()
        val cfg = try {
            RoutingConfig.load(this)
        } catch (e: Exception) {
            lastError = "Protected routing data could not be unlocked"
            stopSelf()
            return
        }

        val builder = Builder()
            .setSession("ShieldProxy")
            .setMtu(9000)
            .addAddress("172.19.0.1", 30)
            .addRoute("0.0.0.0", 0)
            .addDnsServer("172.19.0.2")
            // Always capture IPv6. Omitting ::/0 does not disable IPv6; it lets IPv6-capable
            // apps bypass an IPv4-only VPN through the underlying Nigerian network. When the
            // profile has ipv6=false, Mihomo suppresses AAAA and rejects captured IPv6 safely.
            .addAddress("fdfe:dcba:9876::1", 126)
            .addRoute("::", 0)

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP_MR1) {
            builder.setBlocking(false)
        }

        // Whole-device capture; never route our own traffic back in.
        try {
            builder.addDisallowedApplication(packageName)
        } catch (_: Exception) {
        }

        // CRITICAL: exclude the BlackBox container variants. Their clones route through their OWN
        // per-clone proxy (the container's native connect() redirect). If this VPN also captured
        // the container's traffic, it would hijack the clones' proxy connections (DNS -> fake-ip)
        // and break them (ConnectException). Excluding them lets the whole-phone VPN and per-clone
        // proxies run at the same time without conflict.
        for (container in listOf(
            "top.niunaijun.blackbox", "com.novspace.box",
            "app.cloudvault.multi", "io.prismhub.clone"
        )) {
            try { builder.addDisallowedApplication(container) } catch (_: Exception) {}
        }

        val pfd = try {
            builder.establish()
        } catch (e: Exception) {
            stopSelf(); return
        }
        if (pfd == null) {
            stopSelf(); return
        }
        tun = pfd

        // Mihomo home dir holds config.yaml + downloaded geo/provider files.
        val home = File(filesDir, "mihomo").apply { mkdirs() }
        // Remove any legacy plaintext config left by older builds.
        File(home, "config.yaml").delete()
        val runtimeDir = File(cacheDir, "mihomo-runtime").apply { mkdirs() }
        val configFile = File(runtimeDir, "config.yaml")
        val pm = packageManager
        val uidResolver: (String) -> Int? = { pkg ->
            try {
                pm.getPackageUid(pkg, 0)
            } catch (_: Exception) {
                null
            }
        }
        // Resolve proxy-server hostnames to an IP now, on the underlying network
        // (our app is excluded from the VPN), so Mihomo never needs in-tunnel DNS
        // to reach the proxy. Target domains are still resolved remotely by the
        // proxy via fake-ip.
        val serverResolver: (String) -> String? = { host ->
            if (host.matches(Regex("^[0-9.]+$")) || host.contains(":")) {
                host // already an IP literal
            } else {
                try {
                    java.net.InetAddress.getByName(host).hostAddress
                } catch (_: Exception) {
                    null
                }
            }
        }
        configFile.writeText(cfg.toClashYaml(pfd.fd, uidResolver, serverResolver))

        startForeground(NOTIF_ID, buildNotification(cfg))

        // Protect Mihomo's outbound sockets so proxy connections exit the real
        // network instead of looping back into our own tun.
        val self = this
        MihomoCore.setProtector(object : mobilebridge.Protector {
            override fun protect(fd: Long): Boolean = self.protect(fd.toInt())
        })

        // Per-app routing: resolve each connection's owning app uid via the
        // official getConnectionOwnerUid API (works because we are the active
        // VPN app), so UID/PROCESS rules match on non-rooted Android.
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            val cm = getSystemService(android.net.ConnectivityManager::class.java)
            MihomoCore.setUidResolver(object : mobilebridge.UidQuery {
                override fun query(
                    protocol: Long, srcIp: String, srcPort: Long, destIp: String, destPort: Long
                ): Long {
                    return try {
                        val local = java.net.InetSocketAddress(
                            java.net.InetAddress.getByName(srcIp), srcPort.toInt()
                        )
                        val remote = java.net.InetSocketAddress(
                            java.net.InetAddress.getByName(destIp), destPort.toInt()
                        )
                        cm.getConnectionOwnerUid(protocol.toInt(), local, remote).toLong()
                    } catch (e: Exception) {
                        -1L
                    }
                }
            })
        }

        val err = MihomoCore.start(home.absolutePath, configFile.absolutePath)
        // Mihomo has loaded the configuration; do not retain credentials in a plaintext file.
        runCatching { configFile.delete() }
        if (err.isNotEmpty()) {
            lastError = err
            stopTunnel()
            return
        }
        running = true
    }

    /** Stop the engine + close the tun, but keep the service/foreground alive
     *  (used when switching to another profile). */
    private fun stopEngineOnly() {
        if (running || MihomoCore.running) {
            MihomoCore.stop()
            running = false
        }
        try {
            tun?.close()
        } catch (_: Exception) {
        }
        tun = null
    }

    private fun stopTunnel() {
        watchdog.removeCallbacksAndMessages(null)
        stopEngineOnly()
        stopForeground(STOP_FOREGROUND_REMOVE)
        stopSelf()
    }

    override fun onDestroy() {
        // If the system is killing us but the user still wants routing, DON'T flip
        // wantRunning — START_STICKY will restart us and the watchdog revives the engine.
        watchdog.removeCallbacksAndMessages(null)
        stopEngineOnly()
        super.onDestroy()
    }

    override fun onRevoke() {
        // User revoked VPN consent (or another VPN took over) — stop for real.
        wantRunning = false
        stopTunnel()
        super.onRevoke()
    }

    private fun buildNotification(cfg: RoutingConfig): Notification {
        val nm = getSystemService(NotificationManager::class.java)
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            nm.createNotificationChannel(
                NotificationChannel(CHANNEL_ID, "ShieldProxy", NotificationManager.IMPORTANCE_LOW)
            )
        }
        val open = PendingIntent.getActivity(
            this, 0, Intent(this, MainActivity::class.java), PendingIntent.FLAG_IMMUTABLE
        )
        val nodes = cfg.nodes.count { it.isValid() }
        val mapped = cfg.appMap.size
        return NotificationCompat.Builder(this, CHANNEL_ID)
            .setContentTitle("Routing active")
            .setContentText("$nodes nodes · $mapped apps mapped · ${cfg.processMatchMode.clash}")
            .setSmallIcon(R.drawable.ic_shield)
            .setOngoing(true)
            .setContentIntent(open)
            .build()
    }
}

/** Last engine error, surfaced to the UI. */
@Volatile
var lastError: String = ""
