-- ShieldProxy / ShieldBox — Supabase schema + Row Level Security
-- Run this in the Supabase Dashboard → SQL Editor of the ShieldProxy project
-- (ref oqyrbdvehvqdcpglaojo — NOT the PrivacyShield project).
-- Safe to re-run: guarded with IF NOT EXISTS / CREATE OR REPLACE POLICY.

-- ============================================================================
-- 0. Cleanup — remove the load-test accounts created during setup.
--    (The GoTrue admin DELETE API kept getting dropped from the test machine;
--     real accounts are @gmail, these are all @mailinator, so this is safe.)
-- ============================================================================
-- Test-account cleanup is intentionally not part of this production migration.

-- ============================================================================
-- 1. app_backups  — one config blob per user per app (used by Supabase.pushBackup/pullBackup)
--    NOTE: the app currently upserts with on_conflict=user_id,app, so (user_id, app)
--    must be the primary key / unique.
-- ============================================================================
create table if not exists public.app_backups (
    user_id    uuid        not null default auth.uid() references auth.users (id) on delete cascade,
    app        text        not null,
    data       jsonb       not null default '{}'::jsonb,
    updated_at timestamptz not null default now(),
    primary key (user_id, app)
);

alter table public.app_backups enable row level security;

-- Each user may read/insert/update/delete ONLY their own rows.
drop policy if exists app_backups_select on public.app_backups;
drop policy if exists app_backups_insert on public.app_backups;
drop policy if exists app_backups_update on public.app_backups;
drop policy if exists app_backups_delete on public.app_backups;
create policy app_backups_select on public.app_backups
    for select using (auth.uid() = user_id);
create policy app_backups_insert on public.app_backups
    for insert with check (auth.uid() = user_id);
create policy app_backups_update on public.app_backups
    for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy app_backups_delete on public.app_backups
    for delete using (auth.uid() = user_id);

-- ============================================================================
-- 2. crash_reports — privacy-safe crash reports (CrashReporter -> Supabase.uploadCrashes)
--    The client sends { app, report }; user_id is filled server-side from the JWT.
-- ============================================================================
create table if not exists public.crash_reports (
    id         bigint generated by default as identity primary key,
    user_id    uuid        not null default auth.uid() references auth.users (id) on delete cascade,
    app        text        not null,
    report     jsonb       not null,
    created_at timestamptz not null default now()
);

create index if not exists crash_reports_user_idx on public.crash_reports (user_id, created_at desc);

alter table public.crash_reports enable row level security;

-- Users may INSERT their own reports and SELECT their own; no update/delete from the client.
drop policy if exists crash_reports_insert on public.crash_reports;
drop policy if exists crash_reports_select on public.crash_reports;
create policy crash_reports_insert on public.crash_reports
    for insert with check (auth.uid() = user_id);
create policy crash_reports_select on public.crash_reports
    for select using (auth.uid() = user_id);

-- ============================================================================
-- 3. Auth settings that are NOT SQL — set these in the Dashboard (passwordless OTP):
--    Authentication → Email Templates:
--       • "Magic Link" AND "Confirm signup": replace {{ .ConfirmationURL }} with
--         {{ .Token }} so the email delivers the 6-DIGIT CODE the app asks for.
--    Authentication → SMTP: configure a real sender (Resend/SendGrid/Mailgun).
--       The built-in email caps ~3-4/hour — unusable for many accounts.
--    Authentication → Providers → Email: keep "Confirm email" ON (email is verified
--       by the code). Password sign-in is unused; the app is passwordless OTP.
--    Authentication → Rate Limits: OTP/verify ~30/hour/IP is a sane default.
-- ============================================================================
